### ISSUE TITLE
Port `app-wamr` to use musl

### ISSUE THREAD

**Issue by StefanJum** [unikraft/app-wamr#3]
Port `app-wamr` to use [musl](https://github.com/unikraft/lib-musl), the new supported unikraft glibc.

You should create the `Makefile`  and `Makefile.uk` files.
You can find more information on this on [the Unikraft website](https://unikraft.org/docs/usage/make_build/#extending-the-build).
You can find a list of the external libraries the application depends on in the [`kraft.yaml` file, under the `libraries:` section](https://github.com/unikraft/app-wamr/blob/staging/kraft.yaml#L9-L15).
You will need to replace the `newlib` and `pthread-embedded` dependencies with `musl`.

Hackathon points: 20

**Comment by monikasarakawka** [comment]
Working on this

**Comment by razvand** [comment]
Solved by #5
